### ISSUE TITLE
你好！请教下

### ISSUE THREAD

**Issue by Evanevaneva** [AsprinChina/voltage-transient-stability-analiysis#1]
1、请问样本是通过什么软件仿真获得的呢
2、csv中列标题没有耶，不知道每个特征代表什么

**Comment by AsprinChina** [comment]
样本是PSASP软件生成的，具体包括两步：1、稳态潮流计算，生成初始值；2、机电暂态仿真，模拟某个故障下的电压跌落轨迹，并判断是否失稳，从而生成该样本的标签值。
首列标签，后139列表示139个特征，依次是39个节点的P、Q、V、θ，和故障的类型（均为三相接地）、时间（单位s）、位置。

**Comment by Evanevaneva** [comment]
收到！感谢分享~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chen Binbin <notifications@github.com&gt;
发送时间: 2020年6月4日 16:56
收件人: AsprinChina/voltage-transient-stability-analiysis <voltage-transient-stability-analiysis@noreply.github.com&gt;
抄送: Evanevaneva <1973329369@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[AsprinChina/voltage-transient-stability-analiysis] 你好！请教下 (#1)





 
样本是PSASP软件生成的，具体包括两步：1、稳态潮流计算，生成初始值；2、机电暂态仿真，模拟某个故障下的电压跌落轨迹，并判断是否失稳，从而生成该样本的标签值。
 首列标签，后139列表示139个特征，依次是39个节点的P、Q、V、θ，和故障的类型（均为三相接地）、时间（单位s）、位置。

**Comment by Evanevaneva** [comment]
｡･∀･)ﾉﾞ嗨,按照楼主的方法去做的时候，碰到几个问题：

1.csv文件中的一行是一个样本，那每一个样本是对应一种故障类型，如果我要大量的样本（比如50000个样本），那我不是得仿真50000次才能得到，请问楼主是**如何批量得到**的呢？

2.楼主说先进行潮流计算得到初始值，但是应该是计算故障时的潮流吧？否则 由潮流计算而得到的 139个特征如何和故障发生时的标签对应呢。理论上不应该是 **故障时的标签+故障时的潮流=一个样本吗**？

**Comment by AsprinChina** [comment]
1、确实是一次仿真生成一个样本。可以多进程一起跑，一次仿真也就1s左右，多跑几天基本上足够生成想要的数据了。
2、先进行稳态潮流计算，生成稳态潮流断面（即，故障前断面）。然后，导入故障数据（类型、时间、位置），进行机电潮流仿真，从而判断该故障是否导致失稳，从而生成样本标签。
这里是用故障前的潮流+故障的数据（样本特征），去判断该故障是否导致失稳（样本标签）。

**Comment by Evanevaneva** [comment]
楼主，可以给个机会加个微信吗？这样交流🧐。我的微信:  **arouselyf**
（主要是想学习基于深度学习的暂稳评估，现在卡在样本生成上了...，太难了。）
